const express = require('express')
const app = express()
app.set('view engine','ejs')
var bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
const index = require('./routes/index')
const routerContacts = require('./routes/contacts')
const routerGroups = require('./routes/groups')
const routerAddress = require('./routes/addresses')
const routerProfile = require('./routes/profiles')
app.use('/',index)
app.use('/contacts',routerContacts)
app.use('/groups',routerGroups)
app.use('/addresses',routerAddress)
app.use('/profiles',routerProfile)
app.listen(3000, function(req,res){
  console.log('Listen 3000 success !');
})
